/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'MyApp.view.MainViewViewModel',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.Label',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Check'
    ],

    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            itemId: 'menuPanel',
            width: 150,
            title: 'Menu',
            items: [
                {
                    xtype: 'menu',
                    floating: false,
                    itemId: 'menu',
                    items: [
                        {
                            xtype: 'menuitem',
                            itemId: 'home',
                            text: 'Home',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'about',
                            text: 'About Us',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'contact',
                            text: 'Route Control',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'o4',
                            text: 'Level Assignment',
                            focusable: true
                        }
                    ],
                    listeners: {
                        click: 'onMenuClick'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            itemId: 'contentPanel',
            layout: 'card',
            items: [
                {
                    xtype: 'panel',
                    itemId: 'homePanel',
                    title: 'Home',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'label',
                            text: 'Home View'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'combobox',
                                    id: 'db',
                                    width: 306,
                                    fieldLabel: 'Environment',
                                    value: 'TS',
                                    store: 'storeDB',
                                    valueField: 'id'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'aboutPanel',
                    title: 'About Us',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'label',
                            text: 'About Us View'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'contactPanel',
                    layout: 'fit',
                    title: 'Routing Control',
                    items: [
                        {
                            xtype: 'gridpanel',
                            store: 'storeRtgCtl',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'CTLID',
                                    text: 'ID'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'LVLID',
                                    text: 'Level',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 54,
                                    dataIndex: 'CLS',
                                    text: 'Cls'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 65,
                                    align: 'end',
                                    dataIndex: 'WHS',
                                    text: 'Whs',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'OPTN',
                                    text: 'Option'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ITEM',
                                    text: 'Item'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 56,
                                    align: 'center',
                                    dataIndex: 'SCAN',
                                    text: 'Scan'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 82,
                                    align: 'end',
                                    dataIndex: 'SEQ',
                                    text: 'Seq',
                                    format: '00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 110,
                                    align: 'end',
                                    dataIndex: 'STDPRD',
                                    text: 'Std<br>Production'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'o4Panel',
                    layout: 'fit',
                    title: 'Scan Level Assignment',
                    items: [
                        {
                            xtype: 'gridpanel',
                            store: 'storeRtgLvl',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    width: 65,
                                    dataIndex: 'LVLID',
                                    text: 'ID',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 162,
                                    dataIndex: 'LVLD',
                                    text: 'Description'
                                },
                                {
                                    xtype: 'checkcolumn',
                                    dataIndex: 'PRODLVL',
                                    text: 'Prodlvl'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'SCAN',
                                    text: 'Scan'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 223,
                                    dataIndex: 'SCAND',
                                    text: 'Description'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onMenuClick: function(menu, item, e, eOpts) {
        location.hash = item.itemId;
    }

});