/*
 * File: app/model/modelRtgLvl.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.modelRtgLvl', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            type: 'int',
            name: 'LVLID'
        },
        {
            name: 'LVLD'
        },
        {
            name: 'PRODLVL'
        },
        {
            name: 'SCAN'
        },
        {
            name: 'SCAND'
        }
    ]
});