/*
 * File: app/model/modelRtgCtl.js
 *
 * This file was generated by Sencha Architect version 4.2.7.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.1.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.1.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.modelRtgCtl', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Number',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'float',
            name: 'CTLID'
        },
        {
            type: 'int',
            name: 'LVLID'
        },
        {
            type: 'int',
            name: 'WHS'
        },
        {
            type: 'string',
            name: 'CLS'
        },
        {
            type: 'string',
            name: 'OPTN'
        },
        {
            type: 'string',
            name: 'ITEM'
        },
        {
            type: 'string',
            name: 'SCAN'
        },
        {
            type: 'int',
            name: 'SEQ'
        },
        {
            type: 'float',
            name: 'STDPRD'
        }
    ]
});